/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OtherImport } from './routes/other'

// Create/Update Routes

const OtherRoute = OtherImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/other': typeof OtherRoute
}

export interface FileRoutesByTo {
  '/other': typeof OtherRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/other': typeof OtherRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/other'
  fileRoutesByTo: FileRoutesByTo
  to: '/other'
  id: '__root__' | '/other'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OtherRoute: typeof OtherRoute
}

const rootRouteChildren: RootRouteChildren = {
  OtherRoute: OtherRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/other"
      ]
    },
    "/other": {
      "filePath": "other.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
